function [fitresult, gof] = create_vpmodel(strain_rate, stress)
%CREATEFIT(STRAIN_RATE,STRESS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: strain_rate
%      Y Output: stress
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Oct-2022 19:10:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( strain_rate, stress );

% Set up fittype and options.
ft = fittype( '(a*x^b)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [0.950222048838355 0.0344460805029088 0.933993247757551];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



